apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: eden-api-deployment
  name: eden-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eden-api-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eden-api-app
    spec:
      containers:
      - name: app
        image: arquitectonicos3/eden-app-backend:0.1-SNAPSHOT
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
          - name: DS_HOST
            value: "Hello from the environment"
          - name: DS_PORT
            value: "Such a sweet sorrow"
          - name: DS_NAME
            value: "Such a sweet sorrow"
          - name: DS_USERNAME
            value: "Such a sweet sorrow"
          - name: DS_PASSWORD
            value: "Such a sweet sorrow"