apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: eden-api-deployment
  name: eden-api-deployment
  namespace: placeholder-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eden-api-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eden-api-app
    spec:
      containers:
        - name: app
          image: placeholder-image
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PROFILE
              valueFrom:
                configMapKeyRef:
                  name: eden-app-configmap
                  key: PROFILE
            - name: DS_HOST
              valueFrom:
                configMapKeyRef:
                  name: eden-app-configmap
                  key: DS_HOST
            - name: DS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: eden-app-configmap
                  key: DS_USERNAME
            - name: DS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: eden-app-configmap
                  key: DS_PASSWORD
            - name: S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: eden-app-configmap
                  key: S3_BUCKET_NAME
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: eden-app-configmap
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: eden-app-configmap
                  key: S3_SECRET_ACCESS_KEY