apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-deployment.yml
- app-service.yml
- app-ingress.yml
configMapGenerator:
  - name: eden-app-configmap
    env: config.properties
